'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class labelsProduccion
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.labelsProduccion", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Articulo.
        '''</summary>
        Friend Shared ReadOnly Property articulo() As String
            Get
                Return ResourceManager.GetString("articulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cantidad.
        '''</summary>
        Friend Shared ReadOnly Property cantidad() As String
            Get
                Return ResourceManager.GetString("cantidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cod..
        '''</summary>
        Friend Shared ReadOnly Property codPedido() As String
            Get
                Return ResourceManager.GetString("codPedido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cod..
        '''</summary>
        Friend Shared ReadOnly Property codProduccion() As String
            Get
                Return ResourceManager.GetString("codProduccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comentario.
        '''</summary>
        Friend Shared ReadOnly Property comentario() As String
            Get
                Return ResourceManager.GetString("comentario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diseño.
        '''</summary>
        Friend Shared ReadOnly Property diseño() As String
            Get
                Return ResourceManager.GetString("diseño", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En espera.
        '''</summary>
        Friend Shared ReadOnly Property enEspera() As String
            Get
                Return ResourceManager.GetString("enEspera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En proceso.
        '''</summary>
        Friend Shared ReadOnly Property enProceso() As String
            Get
                Return ResourceManager.GetString("enProceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estado.
        '''</summary>
        Friend Shared ReadOnly Property estado() As String
            Get
                Return ResourceManager.GetString("estado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estado.
        '''</summary>
        Friend Shared ReadOnly Property estadoActual() As String
            Get
                Return ResourceManager.GetString("estadoActual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha dsd. Final.
        '''</summary>
        Friend Shared ReadOnly Property fechaDsdFinal() As String
            Get
                Return ResourceManager.GetString("fechaDsdFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha dsd. Inicio.
        '''</summary>
        Friend Shared ReadOnly Property fechaDsdInicio() As String
            Get
                Return ResourceManager.GetString("fechaDsdInicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha Final.
        '''</summary>
        Friend Shared ReadOnly Property fechaFinal() As String
            Get
                Return ResourceManager.GetString("fechaFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha hsta. Final.
        '''</summary>
        Friend Shared ReadOnly Property fechaHstFinal() As String
            Get
                Return ResourceManager.GetString("fechaHstFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha hsta. Inicio.
        '''</summary>
        Friend Shared ReadOnly Property fechaHstInicio() As String
            Get
                Return ResourceManager.GetString("fechaHstInicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha Inicio.
        '''</summary>
        Friend Shared ReadOnly Property fechaInicio() As String
            Get
                Return ResourceManager.GetString("fechaInicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finalizado.
        '''</summary>
        Friend Shared ReadOnly Property finalizado() As String
            Get
                Return ResourceManager.GetString("finalizado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detalle Produccion.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloDetalle() As String
            Get
                Return ResourceManager.GetString("labelTituloDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lista Produccion.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloLista() As String
            Get
                Return ResourceManager.GetString("labelTituloLista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maquina.
        '''</summary>
        Friend Shared ReadOnly Property maquina() As String
            Get
                Return ResourceManager.GetString("maquina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pedido.
        '''</summary>
        Friend Shared ReadOnly Property pedido() As String
            Get
                Return ResourceManager.GetString("pedido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Realizacion.
        '''</summary>
        Friend Shared ReadOnly Property porcentajeRealizacion() As String
            Get
                Return ResourceManager.GetString("porcentajeRealizacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prenda.
        '''</summary>
        Friend Shared ReadOnly Property prenda() As String
            Get
                Return ResourceManager.GetString("prenda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rezalizacion.
        '''</summary>
        Friend Shared ReadOnly Property realizacion() As String
            Get
                Return ResourceManager.GetString("realizacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comenzar trabajo.
        '''</summary>
        Friend Shared ReadOnly Property RegistrarComienzoTrabajo() As String
            Get
                Return ResourceManager.GetString("RegistrarComienzoTrabajo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finalizar trabajo.
        '''</summary>
        Friend Shared ReadOnly Property RegistrarFinalizacionTrabajo() As String
            Get
                Return ResourceManager.GetString("RegistrarFinalizacionTrabajo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilizacion.
        '''</summary>
        Friend Shared ReadOnly Property utilizacion() As String
            Get
                Return ResourceManager.GetString("utilizacion", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
