'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class labelsMovimientos
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.labelsMovimientos", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cliente .
        '''</summary>
        Friend Shared ReadOnly Property cliente() As String
            Get
                Return ResourceManager.GetString("cliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comentario.
        '''</summary>
        Friend Shared ReadOnly Property comentario() As String
            Get
                Return ResourceManager.GetString("comentario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cuenta.
        '''</summary>
        Friend Shared ReadOnly Property cuenta() As String
            Get
                Return ResourceManager.GetString("cuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha.
        '''</summary>
        Friend Shared ReadOnly Property fecha() As String
            Get
                Return ResourceManager.GetString("fecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha desde.
        '''</summary>
        Friend Shared ReadOnly Property fechaDsd() As String
            Get
                Return ResourceManager.GetString("fechaDsd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha hasta.
        '''</summary>
        Friend Shared ReadOnly Property fechaHst() As String
            Get
                Return ResourceManager.GetString("fechaHst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registrar Pago Cta. Cte..
        '''</summary>
        Friend Shared ReadOnly Property labelTituloCreacionMovimientos() As String
            Get
                Return ResourceManager.GetString("labelTituloCreacionMovimientos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Busqueda Movimientos Cuenta Corriente.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloListaMovimientos() As String
            Get
                Return ResourceManager.GetString("labelTituloListaMovimientos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monto.
        '''</summary>
        Friend Shared ReadOnly Property monto() As String
            Get
                Return ResourceManager.GetString("monto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monto desde.
        '''</summary>
        Friend Shared ReadOnly Property montoDsd() As String
            Get
                Return ResourceManager.GetString("montoDsd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monto hasta.
        '''</summary>
        Friend Shared ReadOnly Property montoHst() As String
            Get
                Return ResourceManager.GetString("montoHst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nro..
        '''</summary>
        Friend Shared ReadOnly Property nroMovimiento() As String
            Get
                Return ResourceManager.GetString("nroMovimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proveedor.
        '''</summary>
        Friend Shared ReadOnly Property proveedor() As String
            Get
                Return ResourceManager.GetString("proveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo cuenta.
        '''</summary>
        Friend Shared ReadOnly Property tipoCuenta() As String
            Get
                Return ResourceManager.GetString("tipoCuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo Movimiento.
        '''</summary>
        Friend Shared ReadOnly Property tipoMovimiento() As String
            Get
                Return ResourceManager.GetString("tipoMovimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo Mov..
        '''</summary>
        Friend Shared ReadOnly Property tipoMovimieto() As String
            Get
                Return ResourceManager.GetString("tipoMovimieto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detalle Pago.
        '''</summary>
        Friend Shared ReadOnly Property tituloDetalle() As String
            Get
                Return ResourceManager.GetString("tituloDetalle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
