'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class labelsDiseño
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.labelsDiseño", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alto.
        '''</summary>
        Friend Shared ReadOnly Property alto() As String
            Get
                Return ResourceManager.GetString("alto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Altura.
        '''</summary>
        Friend Shared ReadOnly Property altura() As String
            Get
                Return ResourceManager.GetString("altura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Altura Desde.
        '''</summary>
        Friend Shared ReadOnly Property alturaDesde() As String
            Get
                Return ResourceManager.GetString("alturaDesde", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Altura Hasta.
        '''</summary>
        Friend Shared ReadOnly Property alturaHasta() As String
            Get
                Return ResourceManager.GetString("alturaHasta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ancho.
        '''</summary>
        Friend Shared ReadOnly Property ancho() As String
            Get
                Return ResourceManager.GetString("ancho", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ancho Desde.
        '''</summary>
        Friend Shared ReadOnly Property anchoDesde() As String
            Get
                Return ResourceManager.GetString("anchoDesde", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ancho Hasta.
        '''</summary>
        Friend Shared ReadOnly Property anchoHasta() As String
            Get
                Return ResourceManager.GetString("anchoHasta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivos.
        '''</summary>
        Friend Shared ReadOnly Property Archivos() As String
            Get
                Return ResourceManager.GetString("Archivos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cantidad.
        '''</summary>
        Friend Shared ReadOnly Property cantidadInsumo() As String
            Get
                Return ResourceManager.GetString("cantidadInsumo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cliente.
        '''</summary>
        Friend Shared ReadOnly Property cliente() As String
            Get
                Return ResourceManager.GetString("cliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descripcion.
        '''</summary>
        Friend Shared ReadOnly Property descripcion() As String
            Get
                Return ResourceManager.GetString("descripcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estado.
        '''</summary>
        Friend Shared ReadOnly Property estado() As String
            Get
                Return ResourceManager.GetString("estado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ficha.
        '''</summary>
        Friend Shared ReadOnly Property ficha() As String
            Get
                Return ResourceManager.GetString("ficha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to id.
        '''</summary>
        Friend Shared ReadOnly Property id() As String
            Get
                Return ResourceManager.GetString("id", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imagen.
        '''</summary>
        Friend Shared ReadOnly Property imagen() As String
            Get
                Return ResourceManager.GetString("imagen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insumo.
        '''</summary>
        Friend Shared ReadOnly Property insumo() As String
            Get
                Return ResourceManager.GetString("insumo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insumos.
        '''</summary>
        Friend Shared ReadOnly Property insumos() As String
            Get
                Return ResourceManager.GetString("insumos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crear Diseño.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloCreacion() As String
            Get
                Return ResourceManager.GetString("labelTituloCreacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detalle Diseño.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloDetalle() As String
            Get
                Return ResourceManager.GetString("labelTituloDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar Diseño.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloEdicion() As String
            Get
                Return ResourceManager.GetString("labelTituloEdicion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Busqueda Diseño.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloLista() As String
            Get
                Return ResourceManager.GetString("labelTituloLista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lista Insumos.
        '''</summary>
        Friend Shared ReadOnly Property listaInsumos() As String
            Get
                Return ResourceManager.GetString("listaInsumos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Matriz Editable.
        '''</summary>
        Friend Shared ReadOnly Property matrizEditable() As String
            Get
                Return ResourceManager.GetString("matrizEditable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Matriz Final.
        '''</summary>
        Friend Shared ReadOnly Property matrizFinal() As String
            Get
                Return ResourceManager.GetString("matrizFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre.
        '''</summary>
        Friend Shared ReadOnly Property nombre() As String
            Get
                Return ResourceManager.GetString("nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Puntadas.
        '''</summary>
        Friend Shared ReadOnly Property puntadas() As String
            Get
                Return ResourceManager.GetString("puntadas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Puntadas desde.
        '''</summary>
        Friend Shared ReadOnly Property puntadasdsd() As String
            Get
                Return ResourceManager.GetString("puntadasdsd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Puntadas hasta.
        '''</summary>
        Friend Shared ReadOnly Property puntadasHasta() As String
            Get
                Return ResourceManager.GetString("puntadasHasta", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
