'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  MaterialesRepositorio.vb
''  Implementation of the Class MaterialesRepositorio
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:28:03 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports Dominio

Public Class MaterialesRepositorio

    Dim colorTdg As ColorTDG
    Dim tipoInsumoTdg As TipoInsumoTDG

    Sub New(ByVal colorTdg As ColorTDG, ByVal tipoInsumoTdg As TipoInsumoTDG)
        Me.tipoInsumoTdg = tipoInsumoTDG
        Me.colorTdg = colorTdg
    End Sub

    Public Function listaMecanicos() As Proveedor()
        Dim retVal As New Proveedor()
        listaMecanicos = Nothing
    End Function

    Public Function listarProveedores() As Proveedor()
        Dim retVal As New Proveedor()
        listarProveedores = Nothing
    End Function

    Public Function listarColores() As List(Of Color)
        Return Me.colorTdg.buscarColor(Nothing)
    End Function

    Public Function listarTipoInsumo() As List(Of TipoInsumo)
        Return Me.tipoInsumoTdg.buscarLista(Nothing)
    End Function

End Class ' MaterialesRepositorio