'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  PermisoPetenteRepositorio.vb
''  Implementation of the Class PermisoPetenteRepositorio
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:28:03 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Public Class PermisoPetenteRepositorio



End Class ' PermisoPetenteRepositorio