'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  PrendaRepositorio.vb
''  Implementation of the Class PrendaRepositorio
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:28:03 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On

Imports Dominio

Public Class TipoPrendaRepositorio

    Dim tdg As TipoPrendaTDG

    Sub New(ByVal tpTDG As TipoPrendaTDG)
        Me.tdg = tpTDG
    End Sub


    Public Sub actualizarTipoPrenda(ByVal tPrenda As TipoPrenda)
        tdg.actualizar(tPrenda)
    End Sub


    Public Sub grabarPrenda(ByVal tPrenda As TipoPrenda)
        tdg.grabar(tPrenda)
    End Sub

    Public Function ListarPrendas() As List(Of TipoPrenda)
        Return tdg.buscarPrendas(Nothing)
    End Function

    Function buscarPrendaPorId(ByVal id As Long) As TipoPrenda
        Dim criteria As New List(Of Restriccion)
        criteria.Add(New Restriccion(TipoPrendaTDG.TIPO_PRENDA, id, Restriccion.CONDICION_IGUAL))

        Return tdg.buscarUnico(criteria)
    End Function

End Class ' PrendaRepositorio
