'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AltaModificacionConversacion

    '''<summary>
    '''tituloEdicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tituloEdicion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''idConversacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents idConversacion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''usuariosPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usuariosPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''nombreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nombreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''usuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usuarios As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''usuarioBusiness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usuarioBusiness As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''mensajeroContenedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mensajeroContenedor As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''conversacionesContenedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents conversacionesContenedor As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''mensajesContenedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mensajesContenedor As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''textoMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents textoMensaje As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''enviarMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents enviarMensaje As Global.System.Web.UI.WebControls.LinkButton
End Class
