'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BusquedaConversacion

    '''<summary>
    '''labelTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''listaConversaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listaConversaciones As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''conversacionBusiness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents conversacionBusiness As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
