'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BusquedaOpinion

    '''<summary>
    '''labelTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''labelmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''labelAnchqqo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelAnchqqo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buscar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''listadoOpiniones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listadoOpiniones As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''opinionBusiness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents opinionBusiness As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
