'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BusquedaOrdenCompra

    '''<summary>
    '''labelTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelnroOrdenCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelnroOrdenCompra As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''nroOrdenCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nroOrdenCompra As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabeltipoOrdenCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabeltipoOrdenCompra As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tipoOrdenCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tipoOrdenCompra As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelnroSucursal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelnroSucursal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''nroSucursal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nroSucursal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelfechaDsd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelfechaDsd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fechaDsd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fechaDsd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelfechaHst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelfechaHst As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fechaHst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fechaHst As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelmontoDsd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelmontoDsd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''montoDsd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents montoDsd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelmontoHst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelmontoHst As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''montoHst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents montoHst As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Labelproveedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelproveedor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''proveedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents proveedor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''proveedorBusiness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents proveedorBusiness As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''labelAnchqqo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelAnchqqo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buscar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''listaOrdenCompras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listaOrdenCompras As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ordenCompraBusiness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ordenCompraBusiness As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
