'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''contenedorArtFrecuentes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contenedorArtFrecuentes As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''art1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents art1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''nombreArt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nombreArt1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cantidad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cantidad1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''generarPedidoArt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents generarPedidoArt1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''art2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents art2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''nombreArt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nombreArt2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cantidad2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cantidad2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''generarPedidoArt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents generarPedidoArt2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''art3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents art3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''nombreArt3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nombreArt3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cantidad3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cantidad3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''generarPedidoArt3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents generarPedidoArt3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''sobreUniprof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sobreUniprof As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''sobre1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sobre1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''sobre2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sobre2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''sobre3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sobre3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''sobre4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sobre4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''sobre5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sobre5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''nosCaracterizamos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nosCaracterizamos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caracteristica1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caracteristica1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caracteristica2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caracteristica2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caracteristica3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caracteristica3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caracteristica4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caracteristica4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caracteristica5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caracteristica5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caracteristica6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caracteristica6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caracteristica7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caracteristica7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''caracteristica8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caracteristica8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''newsletter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newsletter As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''newsletterTittle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newsletterTittle As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''newsletterText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newsletterText As Global.System.Web.UI.WebControls.LinkButton
End Class
