'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class home
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.home", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click aqui para registrarse al newsletter de uniprof.
        '''</summary>
        Friend Shared ReadOnly Property altaNewsletter() As String
            Get
                Return ResourceManager.GetString("altaNewsletter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click aqui para darse de baja al newsletter de uniprof.
        '''</summary>
        Friend Shared ReadOnly Property bajaNewsletter() As String
            Get
                Return ResourceManager.GetString("bajaNewsletter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Corte veloz y preciso sobre cualquier tipo de superficies textiles..
        '''</summary>
        Friend Shared ReadOnly Property caracteristica1() As String
            Get
                Return ResourceManager.GetString("caracteristica1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Produce imágenes en bajo relieve sobre polar y superficies similares..
        '''</summary>
        Friend Shared ReadOnly Property caracteristica2() As String
            Get
                Return ResourceManager.GetString("caracteristica2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Removiendo el pigmento en las telas produce un grabado, especial para jeans y gabardina..
        '''</summary>
        Friend Shared ReadOnly Property caracteristica3() As String
            Get
                Return ResourceManager.GetString("caracteristica3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logra cortes de varias aplicaciones superpuestas..
        '''</summary>
        Friend Shared ReadOnly Property caracteristica4() As String
            Get
                Return ResourceManager.GetString("caracteristica4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logra calados removiendo la superficie del tejido mostrando la superficie por debajo en combinación con bordado..
        '''</summary>
        Friend Shared ReadOnly Property caracteristica5() As String
            Get
                Return ResourceManager.GetString("caracteristica5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cortes en alto nivel de detalle en escudos y parches..
        '''</summary>
        Friend Shared ReadOnly Property caracteristica6() As String
            Get
                Return ResourceManager.GetString("caracteristica6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Corte veloz y preciso sobre cualquier tipo de superficies textiles..
        '''</summary>
        Friend Shared ReadOnly Property caracteristica7() As String
            Get
                Return ResourceManager.GetString("caracteristica7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Produce imágenes en bajo relieve sobre polar y superficies similares..
        '''</summary>
        Friend Shared ReadOnly Property caracteristica8() As String
            Get
                Return ResourceManager.GetString("caracteristica8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copyright 2012, Uniprof. Diseñado por.
        '''</summary>
        Friend Shared ReadOnly Property footer() As String
            Get
                Return ResourceManager.GetString("footer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mail.
        '''</summary>
        Friend Shared ReadOnly Property mail() As String
            Get
                Return ResourceManager.GetString("mail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre.
        '''</summary>
        Friend Shared ReadOnly Property nombre() As String
            Get
                Return ResourceManager.GetString("nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nos caracterizamos por.
        '''</summary>
        Friend Shared ReadOnly Property nosCaracterizamos() As String
            Get
                Return ResourceManager.GetString("nosCaracterizamos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to opinion.
        '''</summary>
        Friend Shared ReadOnly Property opinion() As String
            Get
                Return ResourceManager.GetString("opinion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pedidos frecuentes.
        '''</summary>
        Friend Shared ReadOnly Property pedidosFrecuentes() As String
            Get
                Return ResourceManager.GetString("pedidosFrecuentes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Realizamos bordados para empresas de moda, de artículos de promoción, colegios, clubes y toda empresa que quiera desarrollar un bordado con su propio diseño o marca..
        '''</summary>
        Friend Shared ReadOnly Property sobre1() As String
            Get
                Return ResourceManager.GetString("sobre1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trabajamos sobre todo tipo de telas y texturas, prendas o productos en proceso de elaboración, diseños multicolor, apliques bordados, escudos, logos y gorras. Contamos con la maquinaria para desarrollar bordados para aplicar a sus diseños lentejuelas, mostacillas, canutillos y cordones..
        '''</summary>
        Friend Shared ReadOnly Property sobre2() As String
            Get
                Return ResourceManager.GetString("sobre2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incorporamos la última tecnología en corte laser aplicado al mundo del bordado. Permite realizar cortes muy exactos para el trabajo de aplicaciones en telas logrando diseños imposibles de realizar a mano..
        '''</summary>
        Friend Shared ReadOnly Property sobre3() As String
            Get
                Return ResourceManager.GetString("sobre3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Realizamos bordados para empresas de moda, de artículos de promoción, colegios, clubes y toda empresa que quiera desarrollar un bordado con su propio diseño o marca..
        '''</summary>
        Friend Shared ReadOnly Property sobre4() As String
            Get
                Return ResourceManager.GetString("sobre4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trabajamos sobre todo tipo de telas y texturas, prendas o productos en proceso de elaboración, diseños multicolor, apliques bordados, escudos, logos y gorras. Contamos con la maquinaria para desarrollar bordados para aplicar a sus diseños lentejuelas, mostacillas, canutillos y cordones..
        '''</summary>
        Friend Shared ReadOnly Property sobre5() As String
            Get
                Return ResourceManager.GetString("sobre5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sobre Uniprof.
        '''</summary>
        Friend Shared ReadOnly Property sobreUniprof() As String
            Get
                Return ResourceManager.GetString("sobreUniprof", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ha llegado el envío esta misma tarde. Agradecerte de nuevo vuestra rapidez y correcta gestión. Un placer trabajar con vosotros..
        '''</summary>
        Friend Shared ReadOnly Property testimonio1() As String
            Get
                Return ResourceManager.GetString("testimonio1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pedido recibido, los polos son geniales! Gracias por hacerlo todo tan bien y tan rápido. Contaremos con vosotros para más proyectos ;).
        '''</summary>
        Friend Shared ReadOnly Property testimonio2() As String
            Get
                Return ResourceManager.GetString("testimonio2", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
