'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class labelsInsumo
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.labelsInsumo", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cantidad.
        '''</summary>
        Friend Shared ReadOnly Property cantidad() As String
            Get
                Return ResourceManager.GetString("cantidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cod..
        '''</summary>
        Friend Shared ReadOnly Property codInsumo() As String
            Get
                Return ResourceManager.GetString("codInsumo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color.
        '''</summary>
        Friend Shared ReadOnly Property color() As String
            Get
                Return ResourceManager.GetString("color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Costo.
        '''</summary>
        Friend Shared ReadOnly Property costo() As String
            Get
                Return ResourceManager.GetString("costo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detalle.
        '''</summary>
        Friend Shared ReadOnly Property detalle() As String
            Get
                Return ResourceManager.GetString("detalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha.
        '''</summary>
        Friend Shared ReadOnly Property fecha() As String
            Get
                Return ResourceManager.GetString("fecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crear Insumo.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloCreacion() As String
            Get
                Return ResourceManager.GetString("labelTituloCreacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar Insumo.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloEdicion() As String
            Get
                Return ResourceManager.GetString("labelTituloEdicion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Listado Insumos.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloLista() As String
            Get
                Return ResourceManager.GetString("labelTituloLista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre.
        '''</summary>
        Friend Shared ReadOnly Property nombre() As String
            Get
                Return ResourceManager.GetString("nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nro.
        '''</summary>
        Friend Shared ReadOnly Property nroMovimiento() As String
            Get
                Return ResourceManager.GetString("nroMovimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo Insumo.
        '''</summary>
        Friend Shared ReadOnly Property tipo() As String
            Get
                Return ResourceManager.GetString("tipo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detalle Insumo.
        '''</summary>
        Friend Shared ReadOnly Property tituloDetalle() As String
            Get
                Return ResourceManager.GetString("tituloDetalle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
