'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  PrendaBusiness.vb
''  Implementation of the Class PrendaBusiness
''  Generated by Enterprise Architect
''  Created on:      20-ago-2012 04:41:59 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports Dominio

Public Class PrendaBusiness


    ''' 
    ''' <param name="nombre"></param>
    ''' <param name="maquina"></param>
    Public Sub crearTipoPrenda(ByVal nombre As String, ByVal maquina As Maquina)

    End Sub

    ''' 
    ''' <param name="prenda"></param>
    Public Sub eliminarTipoPrenda(ByVal prenda As TipoPrenda)

    End Sub

    Public Function listarPrendas() As TipoPrenda()
        Dim retVal As TipoPrenda()
        listarPrendas = retVal
    End Function


End Class ' PrendaBusiness