'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class labels
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.labels", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El alto debe ser numerico XX,XX  o XX.
        '''</summary>
        Friend Shared ReadOnly Property alturaInvalido() As String
            Get
                Return ResourceManager.GetString("alturaInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El ancho debe ser numerico XX,XX  o XX.
        '''</summary>
        Friend Shared ReadOnly Property anchoInvalido() As String
            Get
                Return ResourceManager.GetString("anchoInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Atencion.
        '''</summary>
        Friend Shared ReadOnly Property atencion() As String
            Get
                Return ResourceManager.GetString("atencion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Año.
        '''</summary>
        Friend Shared ReadOnly Property año() As String
            Get
                Return ResourceManager.GetString("año", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar.
        '''</summary>
        Friend Shared ReadOnly Property Buscar() As String
            Get
                Return ResourceManager.GetString("Buscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El campo cabezales debe ser numerico.
        '''</summary>
        Friend Shared ReadOnly Property cabezalesInvalido() As String
            Get
                Return ResourceManager.GetString("cabezalesInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calidad.
        '''</summary>
        Friend Shared ReadOnly Property calidad() As String
            Get
                Return ResourceManager.GetString("calidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Existen campos requeridos vacios.
        '''</summary>
        Friend Shared ReadOnly Property camposRequeridos() As String
            Get
                Return ResourceManager.GetString("camposRequeridos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelar.
        '''</summary>
        Friend Shared ReadOnly Property cancelar() As String
            Get
                Return ResourceManager.GetString("cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La cantidad debe ser numerico XX,XX o XX.
        '''</summary>
        Friend Shared ReadOnly Property cantidadInvalido() As String
            Get
                Return ResourceManager.GetString("cantidadInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El campo colores debe ser numerico.
        '''</summary>
        Friend Shared ReadOnly Property coloresInvalido() As String
            Get
                Return ResourceManager.GetString("coloresInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enviar y confirmar baja newsletter.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmarEnviar() As String
            Get
                Return ResourceManager.GetString("ConfirmarEnviar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property contraseña() As String
            Get
                Return ResourceManager.GetString("contraseña", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Costos por insumos (Mes).
        '''</summary>
        Friend Shared ReadOnly Property costoInsumos() As String
            Get
                Return ResourceManager.GetString("costoInsumos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El campo costo solo admite valores numericos XXX,XX.
        '''</summary>
        Friend Shared ReadOnly Property costoInvalido() As String
            Get
                Return ResourceManager.GetString("costoInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar.
        '''</summary>
        Friend Shared ReadOnly Property editar() As String
            Get
                Return ResourceManager.GetString("editar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eficiencia.
        '''</summary>
        Friend Shared ReadOnly Property eficiencia() As String
            Get
                Return ResourceManager.GetString("eficiencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Encuesta Calidad.
        '''</summary>
        Friend Shared ReadOnly Property encuestaCalidad() As String
            Get
                Return ResourceManager.GetString("encuestaCalidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lamentablemente usted no posee los permisos necesarios para acceder a la pagina.
        '''</summary>
        Friend Shared ReadOnly Property errorPermisos() As String
            Get
                Return ResourceManager.GetString("errorPermisos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El pedido debe tener al menos un trabajo.
        '''</summary>
        Friend Shared ReadOnly Property faltaTrabajo() As String
            Get
                Return ResourceManager.GetString("faltaTrabajo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to grabar.
        '''</summary>
        Friend Shared ReadOnly Property grabar() As String
            Get
                Return ResourceManager.GetString("grabar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingresar.
        '''</summary>
        Friend Shared ReadOnly Property ingresar() As String
            Get
                Return ResourceManager.GetString("ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No exsinten resultados para la busqueda realizada.
        '''</summary>
        Friend Shared ReadOnly Property listaVacia() As String
            Get
                Return ResourceManager.GetString("listaVacia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log in.
        '''</summary>
        Friend Shared ReadOnly Property loguerse() As String
            Get
                Return ResourceManager.GetString("loguerse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El mail ingresado no es un mail valido.
        '''</summary>
        Friend Shared ReadOnly Property mailInvalido() As String
            Get
                Return ResourceManager.GetString("mailInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maquina.
        '''</summary>
        Friend Shared ReadOnly Property maquina() As String
            Get
                Return ResourceManager.GetString("maquina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El campo monto solo admite valores numericos XXX,XX.
        '''</summary>
        Friend Shared ReadOnly Property montoInvalido() As String
            Get
                Return ResourceManager.GetString("montoInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El campo precio solo admite valores numericos XXX,XX.
        '''</summary>
        Friend Shared ReadOnly Property precioInvalido() As String
            Get
                Return ResourceManager.GetString("precioInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Produccion Por Maquina (mes).
        '''</summary>
        Friend Shared ReadOnly Property produccionPorMaquina() As String
            Get
                Return ResourceManager.GetString("produccionPorMaquina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Las puntadas debe ser numerico .
        '''</summary>
        Friend Shared ReadOnly Property puntadasInvalido() As String
            Get
                Return ResourceManager.GetString("puntadasInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crear Usuario.
        '''</summary>
        Friend Shared ReadOnly Property registracion() As String
            Get
                Return ResourceManager.GetString("registracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione.
        '''</summary>
        Friend Shared ReadOnly Property Seleccione() As String
            Get
                Return ResourceManager.GetString("Seleccione", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El telefono debe tener el formato de XX-XXXX-XXXX o XXXX-XXXX.
        '''</summary>
        Friend Shared ReadOnly Property telefonoInvalido() As String
            Get
                Return ResourceManager.GetString("telefonoInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El telefono Fijo debe tener el formato de XXXX-XXXX.
        '''</summary>
        Friend Shared ReadOnly Property telFijoInvalido() As String
            Get
                Return ResourceManager.GetString("telFijoInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El telefono Movil debe tener el formato de XX-XXXX-XXXX.
        '''</summary>
        Friend Shared ReadOnly Property telMovilInvalido() As String
            Get
                Return ResourceManager.GetString("telMovilInvalido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estadisticas.
        '''</summary>
        Friend Shared ReadOnly Property tituloEstadisticas() As String
            Get
                Return ResourceManager.GetString("tituloEstadisticas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usuario.
        '''</summary>
        Friend Shared ReadOnly Property usuario() As String
            Get
                Return ResourceManager.GetString("usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ventas Por mes.
        '''</summary>
        Friend Shared ReadOnly Property ventasPorMes() As String
            Get
                Return ResourceManager.GetString("ventasPorMes", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
