'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class labelsArticulo
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.labelsArticulo", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Articulo.
        '''</summary>
        Friend Shared ReadOnly Property articulo() As String
            Get
                Return ResourceManager.GetString("articulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cod..
        '''</summary>
        Friend Shared ReadOnly Property codArticulo() As String
            Get
                Return ResourceManager.GetString("codArticulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comentario.
        '''</summary>
        Friend Shared ReadOnly Property comentario() As String
            Get
                Return ResourceManager.GetString("comentario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diseño.
        '''</summary>
        Friend Shared ReadOnly Property diseño() As String
            Get
                Return ResourceManager.GetString("diseño", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desde.
        '''</summary>
        Friend Shared ReadOnly Property fechaDesde() As String
            Get
                Return ResourceManager.GetString("fechaDesde", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hasta.
        '''</summary>
        Friend Shared ReadOnly Property fechaHasta() As String
            Get
                Return ResourceManager.GetString("fechaHasta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crear Articulo.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloCreacion() As String
            Get
                Return ResourceManager.GetString("labelTituloCreacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detalle Articulo.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloDetalle() As String
            Get
                Return ResourceManager.GetString("labelTituloDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar Articulo.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloEdicion() As String
            Get
                Return ResourceManager.GetString("labelTituloEdicion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Busqueda Articulo.
        '''</summary>
        Friend Shared ReadOnly Property labelTituloLista() As String
            Get
                Return ResourceManager.GetString("labelTituloLista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nro..
        '''</summary>
        Friend Shared ReadOnly Property nroLista() As String
            Get
                Return ResourceManager.GetString("nroLista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precio.
        '''</summary>
        Friend Shared ReadOnly Property precio() As String
            Get
                Return ResourceManager.GetString("precio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precio.
        '''</summary>
        Friend Shared ReadOnly Property precioActual() As String
            Get
                Return ResourceManager.GetString("precioActual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Produccion.
        '''</summary>
        Friend Shared ReadOnly Property produccion() As String
            Get
                Return ResourceManager.GetString("produccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo Prenda.
        '''</summary>
        Friend Shared ReadOnly Property tipoPrenda() As String
            Get
                Return ResourceManager.GetString("tipoPrenda", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
