'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  Articulo.vb
''  Implementation of the Class Articulo
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:31 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

<Serializable()>
Public Class Articulo

    Private _codArticulo As Long
    Private _comentario As String
    Private _precioActual As Double
    Private _tipoPrenda As TipoPrenda
    Private _diseño As Diseño
    Private _listaPrecios As List(Of ListaPrecios)
    Private _borrado As Boolean
    Private _produccion As Integer

    Sub New(ByVal cod As Long, ByVal com As String, ByVal precio As Double, ByVal produccion As Integer,
            ByVal tipo As TipoPrenda, ByVal diseño As Diseño, ByVal listaPrecios As List(Of ListaPrecios))
        Me.codArticulo = cod
        Me.comentario = com
        Me.precioActual = precio
        Me.tipoPrenda = tipo
        Me.produccion = produccion
        Me.diseño = diseño
        Me.listaPrecios = listaPrecios

        If Not listaPrecios Is Nothing Then
            For Each precioLista As ListaPrecios In listaPrecios
                precioLista.articulo = Me
            Next
        End If
    End Sub

    Sub New(ByVal codArticulo As Long)
        Me.codArticulo = codArticulo
    End Sub

    Sub New()

    End Sub

    Public Property codArticulo() As Long
        Get
            Return _codArticulo
        End Get
        Set(ByVal value As Long)
            _codArticulo = value
        End Set
    End Property

    Public Property listaPrecios() As List(Of ListaPrecios)
        Get
            Return _listaPrecios
        End Get
        Set(ByVal Value As List(Of ListaPrecios))
            _listaPrecios = Value
        End Set
    End Property

    Public Property precioActual() As Double
        Get
            Return _precioActual
        End Get
        Set(ByVal Value As Double)
            _precioActual = Value
        End Set
    End Property

    Public Property produccion() As Integer
        Get
            Return _produccion
        End Get
        Set(ByVal value As Integer)
            _produccion = value
        End Set
    End Property


    Public Property tipoPrenda() As TipoPrenda
        Get
            Return _tipoPrenda
        End Get
        Set(ByVal Value As TipoPrenda)
            _tipoPrenda = Value
        End Set
    End Property

    Public Property comentario() As String
        Get
            Return _comentario
        End Get
        Set(ByVal Value As String)
            _comentario = Value
        End Set
    End Property

    Public Property diseño() As Diseño
        Get
            Return _diseño
        End Get
        Set(ByVal Value As Diseño)
            _diseño = Value
        End Set
    End Property

    Public Property borrado() As Boolean
        Get
            Return _borrado
        End Get
        Set(ByVal value As Boolean)
            _borrado = value
        End Set
    End Property

    Public Overrides Function ToString() As String
        Return Me.diseño.nombre + " - " + Me.tipoPrenda.descripcion
    End Function

End Class ' Articulo
