'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  Color.vb
''  Implementation of the Class Color
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:31 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class Color

    Private _codColor As Long
    Private _color As String

    Sub New(ByVal cod As Long)
        Me.codColor = cod
    End Sub

    Sub New()

    End Sub

    Public Property codColor() As Long
        Get
            Return _codColor
        End Get
        Set(ByVal value As Long)
            _codColor = value
        End Set
    End Property

    Public Property color() As String
        Get
            Return _color
        End Get
        Set(ByVal Value As String)
            _color = Value
        End Set
    End Property

    Public Overrides Function ToString() As String
        Return Me.color
    End Function

End Class ' Color