'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  Documento.vb
''  Implementation of the Class Documento
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:32 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Option Explicit On

<Serializable()>
Public Class Documento

    Private _nroDocumento As Long
    Private _movimientoCuenta As MovimientosCuenta
    Private _iva As Double
    Private _fecha As DateTime
    Private _borrado As Boolean
    Private _monto As Double

    Sub New(ByVal nro As Long, ByVal mov As MovimientosCuenta, ByVal iva As Double, ByVal fecha As DateTime, ByVal borrado As Boolean, ByVal monto As Double)
        Me.nroDocumento = nro
        Me.movimientoCuenta = mov
        Me.iva = iva
        Me.fecha = fecha
        Me.monto = monto
        Me.borrado = borrado
    End Sub

    Sub New(ByVal id As Long)
        Me.nroDocumento = id
    End Sub

    Sub New()

    End Sub

    Public Property nroDocumento() As Long
        Get
            Return _nroDocumento
        End Get
        Set(ByVal Value As Long)
            _nroDocumento = Value
        End Set
    End Property

    Public Property movimientoCuenta() As MovimientosCuenta
        Get
            Return _movimientoCuenta
        End Get
        Set(ByVal Value As MovimientosCuenta)
            _movimientoCuenta = Value
            If Not Value Is Nothing Then
                Value.documento = Me
            End If
        End Set
    End Property

    Public Property iva() As Double
        Get
            Return _iva
        End Get
        Set(ByVal Value As Double)
            _iva = Value
        End Set
    End Property

    Public Property fecha() As DateTime
        Get
            Return _fecha
        End Get
        Set(ByVal Value As DateTime)
            _fecha = Value
        End Set
    End Property

    Public Property borrado() As Boolean
        Get
            Return _borrado
        End Get
        Set(ByVal value As Boolean)
            _borrado = value
        End Set
    End Property

    Public Property monto() As Double
        Get
            Return _monto
        End Get
        Set(ByVal value As Double)
            _monto = value
        End Set
    End Property

End Class ' Documento
