'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  EstadoTrabajos.vb
''  Implementation of the Class EstadoTrabajos
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:32 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class EstadoTrabajos

    Private _estado As Long
    Private _descripcion As String

    Sub New()

    End Sub

    Sub New(ByVal id As Long)
        Me.estado = id
    End Sub

    Public Property estado() As Long
        Get
            Return _estado
        End Get
        Set(ByVal Value As Long)
            _estado = Value
        End Set
    End Property

    Public Property descripcion() As String
        Get
            Return _descripcion
        End Get
        Set(ByVal Value As String)
            _descripcion = Value
        End Set
    End Property

End Class ' EstadoTrabajos