'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  EstadoPedido.vb
''  Implementation of the Class EstadoPedido
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:32 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class EstadoPedido

    Private _estadoPedido As Long
    Private _descripcion As String

    Sub New()

    End Sub

    Sub New(ByVal id As Long)
        Me.estadoPedido = id
    End Sub

    Public Property estadoPedido() As Long
        Get
            Return _estadoPedido
        End Get
        Set(ByVal Value As Long)
            _estadoPedido = Value
        End Set
    End Property

    Public Property descripcion() As String
        Get
            Return _descripcion
        End Get
        Set(ByVal Value As String)
            _descripcion = Value
        End Set
    End Property

    Public Overrides Function ToString() As String
        Return Me.descripcion
    End Function

End Class ' EstadoPedido
