'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  Factura.vb
''  Implementation of the Class Factura
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:32 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class Factura
    Inherits Documento

    Private _nroFactura As Long
    Private _nroSucursal As Long
    Private _tipoFactura As String
    Private _cliente As Cliente
    Private _LineasFactura As List(Of LineaFactura)

    Sub New(ByVal nro As Long, ByVal mov As MovimientosCuenta, ByVal iva As Double, ByVal monto As Double, ByVal fecha As DateTime, ByVal borrado As Boolean,
            ByVal nroFactura As Long, ByVal nroSucursal As Long, ByVal tipoFactura As String, ByVal cliente As Cliente, ByVal lineas As List(Of LineaFactura))
        MyBase.New(nro, mov, iva, fecha, borrado, monto)
        Me.nroFactura = nroFactura
        Me.nroSucursal = nroSucursal
        Me.tipoFactura = tipoFactura
        Me.cliente = cliente
        Me.lineas = lineas

        If Not lineas Is Nothing Then
            For Each linea As LineaFactura In lineas
                linea.factura = Me
            Next
        End If
    End Sub

    Sub New(ByVal nroFac As Long, ByVal nroSuc As Long, ByVal tipo As String)
        Me.nroFactura = nroFac
        Me.nroSucursal = nroSuc
        Me.tipoFactura = tipo
    End Sub

    Sub New()

    End Sub

    Public Property nroFactura() As Long
        Get
            Return _nroFactura
        End Get
        Set(ByVal Value As Long)
            _nroFactura = Value
        End Set
    End Property

    Public Property nroSucursal() As Long
        Get
            Return _nroSucursal
        End Get
        Set(ByVal Value As Long)
            _nroSucursal = Value
        End Set
    End Property

    Public Property tipoFactura() As String
        Get
            Return _tipoFactura
        End Get
        Set(ByVal Value As String)
            _tipoFactura = Value
        End Set
    End Property

    Public Property lineas() As List(Of LineaFactura)
        Get
            Return _LineasFactura
        End Get
        Set(ByVal Value As List(Of LineaFactura))
            _LineasFactura = Value
        End Set
    End Property

    Public Property cliente() As Cliente
        Get
            Return _cliente
        End Get
        Set(ByVal Value As Cliente)
            _cliente = Value
        End Set
    End Property

End Class ' Factura