'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  HistoricoEstadosDiseño.vb
''  Implementation of the Class HistoricoEstadosDiseño
''  Generated by Enterprise Architect
''  Created on:      08-sep-2012 01:50:01 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On

<Serializable()>
Public Class HistoricoEstadosDiseño

    Private _nroEstado As Long
    Private _diseño As Diseño
    Private _fechaDesde As DateTime
    Private _fechaHasta As DateTime
    Private _estado As EstadoDiseños
    Private _comentario As String
    Private _borrado As Boolean

    Sub New()

    End Sub

    Sub New(ByVal nro As Long, ByVal diseño As Diseño, ByVal comentario As String,
        ByVal desde As DateTime, ByVal hasta As DateTime, ByVal estado As EstadoDiseños)
        Me.nroEstado = nro
        Me.diseño = diseño
        Me.comentario = comentario
        Me.fechaDesde = desde
        Me.fechaHasta = hasta
        Me.estado = estado
    End Sub

    Public Property fechaDesde() As DateTime
        Get
            Return _fechaDesde
        End Get
        Set(ByVal Value As DateTime)
            _fechaDesde = Value
        End Set
    End Property

    Public Property comentario() As String
        Get
            Return _comentario
        End Get
        Set(ByVal Value As String)
            _comentario = Value
        End Set
    End Property

    Public Property fechaHasta() As DateTime
        Get
            Return _fechaHasta
        End Get
        Set(ByVal Value As DateTime)
            _fechaHasta = Value
        End Set
    End Property

    Public Property nroEstado() As Long
        Get
            Return _nroEstado
        End Get
        Set(ByVal Value As Long)
            _nroEstado = Value
        End Set
    End Property

    Public Property diseño() As Diseño
        Get
            Return _diseño
        End Get
        Set(ByVal Value As Diseño)
            _diseño = Value
        End Set
    End Property

    Public Property estado() As EstadoDiseños
        Get
            Return _estado
        End Get
        Set(ByVal Value As EstadoDiseños)
            _estado = Value
        End Set
    End Property

    Public Property borrado() As Boolean
        Get
            Return _borrado
        End Get
        Set(ByVal value As Boolean)
            _borrado = value
        End Set
    End Property

End Class ' HistoricoEstadosDiseño