'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  HistoricoProduccion.vb
''  Implementation of the Class HistoricoProduccion
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:33 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class HistoricoProduccion

    Private _nroEstado As Long
    Private _produccion As Produccion
    Private _comentario As String
    Private _fechaDesde As DateTime
    Private _fechaHasta As DateTime
    Private _estadoTrabajos As EstadoTrabajos

    Sub New()

    End Sub

    Sub New(ByVal nro As Long, ByVal trabajo As Produccion, ByVal comentario As String,
            ByVal desde As DateTime, ByVal hasta As DateTime, ByVal estado As EstadoTrabajos)
        Me.nroEstado = nro
        Me.produccion = trabajo
        Me.comentario = comentario
        Me.fechaDesde = desde
        Me.fechaHasta = hasta
        Me.estadoTrabajo = estado
    End Sub

    Private _borrado As Boolean
    Public Property nroEstado() As Long
        Get
            Return _nroEstado
        End Get
        Set(ByVal value As Long)
            _nroEstado = value
        End Set
    End Property

    Public Property fechaHasta() As DateTime
        Get
            Return _fechaHasta
        End Get
        Set(ByVal Value As DateTime)
            _fechaHasta = Value
        End Set
    End Property

    Public Property fechaDesde() As DateTime
        Get
            Return _fechaDesde
        End Get
        Set(ByVal Value As DateTime)
            _fechaDesde = Value
        End Set
    End Property

    Public Property comentario() As String
        Get
            Return _comentario
        End Get
        Set(ByVal Value As String)
            _comentario = Value
        End Set
    End Property

    Public Property produccion() As Produccion
        Get
            Return _produccion
        End Get
        Set(ByVal value As Produccion)
            _produccion = value
        End Set
    End Property

    Public Property estadoTrabajo() As EstadoTrabajos
        Get
            Return _estadoTrabajos
        End Get
        Set(ByVal value As EstadoTrabajos)
            _estadoTrabajos = value
        End Set
    End Property

    Public Property borrado() As Boolean
        Get
            Return _borrado
        End Get
        Set(ByVal value As Boolean)
            _borrado = value
        End Set
    End Property

End Class ' HistoricoProduccion
