'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  LineaOrdenDeCompra.vb
''  Implementation of the Class LineaOrdenDeCompra
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:34 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class LineaOrdenDeCompra

    Private _ordenDeCompra As OrdenDeCompra
    Private _nroLinea As Long
    Private _cantidad As Integer
    Private _precio As Double
    Private _articulo As Insumo
    Private _borrado As Boolean

    Sub New(ByVal nroLinea As Long, ByVal insumo As Insumo, ByVal cant As Integer,
            ByVal precio As Double, ByVal orden As OrdenDeCompra, ByVal borrado As Boolean)
        Me.nroLinea = nroLinea
        Me.articulo = insumo
        Me.cantidad = cant
        Me.precio = precio
        Me.ordenDeCompra = orden
        Me.borrado = borrado
    End Sub

    Sub New()

    End Sub

    Public Property ordenDeCompra() As OrdenDeCompra
        Get
            Return _ordenDeCompra
        End Get
        Set(ByVal Value As OrdenDeCompra)
            _ordenDeCompra = Value
        End Set
    End Property

    Public Property nroLinea() As Long
        Get
            Return _nroLinea
        End Get
        Set(ByVal Value As Long)
            _nroLinea = Value
        End Set
    End Property

    Public Property cantidad() As Integer
        Get
            Return _cantidad
        End Get
        Set(ByVal Value As Integer)
            _cantidad = Value
        End Set
    End Property

    Public Property precio() As Double
        Get
            Return _precio
        End Get
        Set(ByVal Value As Double)
            _precio = Value
        End Set
    End Property

    Public Property articulo() As Insumo
        Get
            Return _articulo
        End Get
        Set(ByVal Value As Insumo)
            _articulo = Value
        End Set
    End Property

    Public Property borrado() As Boolean
        Get
            Return _borrado
        End Get
        Set(ByVal value As Boolean)
            _borrado = value
        End Set
    End Property

End Class ' LineaOrdenDeCompra