'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  Maquina.vb
''  Implementation of the Class Maquina
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:34 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class Maquina

    Private _codMaquina As Long
    Private _altoMargen As Integer
    Private _anchoMargen As Integer
    Private _cabezales As Integer
    Private _nombre As String
    Private _velocidadPromedio As Integer
    Private _tipoPrenda As List(Of TipoPrenda)
    Private _cantidadColores As Integer

    Sub New(ByVal cod As Long, ByVal alto As Integer, ByVal ancho As Integer, ByVal cabezales As Integer,
            ByVal nombre As String, ByVal velPromedio As Integer, ByVal tipos As List(Of TipoPrenda),
            ByVal cantColores As Integer)
        Me.codMaquina = cod
        Me.altoMargen = alto
        Me.anchoMargen = ancho
        Me.cabezales = cabezales
        Me.nombre = nombre
        Me.velocidadPromedio = velPromedio
        Me.tiposPrenda = tipos
        Me.cantidadColores = cantColores
    End Sub

    Sub New(ByVal codMaquina As Integer)
        Me.codMaquina = codMaquina
    End Sub

    Sub New()

    End Sub

    Public Property altoMargen() As Integer
        Get
            Return _altoMargen
        End Get
        Set(ByVal Value As Integer)
            _altoMargen = Value
        End Set
    End Property

    Public Property anchoMargen() As Integer
        Get
            Return _anchoMargen
        End Get
        Set(ByVal Value As Integer)
            _anchoMargen = Value
        End Set
    End Property

    Public Property cabezales() As Integer
        Get
            Return _cabezales
        End Get
        Set(ByVal Value As Integer)
            _cabezales = Value
        End Set
    End Property

    Public Property nombre() As String
        Get
            Return _nombre
        End Get
        Set(ByVal Value As String)
            _nombre = Value
        End Set
    End Property

    Public Property velocidadPromedio() As Integer
        Get
            Return _velocidadPromedio
        End Get
        Set(ByVal Value As Integer)
            _velocidadPromedio = Value
        End Set
    End Property

    Public Property codMaquina() As Long
        Get
            Return _codMaquina
        End Get
        Set(ByVal Value As Long)
            _codMaquina = Value
        End Set
    End Property

    Public Property tiposPrenda() As List(Of TipoPrenda)
        Get
            Return _tipoPrenda
        End Get
        Set(ByVal Value As List(Of TipoPrenda))
            _tipoPrenda = Value
        End Set
    End Property

    Public Property cantidadColores() As Integer
        Get
            Return _cantidadColores
        End Get
        Set(ByVal value As Integer)
            _cantidadColores = value
        End Set
    End Property

End Class ' Maquina