'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  MovimientosCuentaProveedor.vb
''  Implementation of the Class MovimientosCuentaProveedor
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:35 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On

<Serializable()>
Public Class MovimientosCuentaProveedor
    Inherits MovimientosCuenta

    Private _proveedor As Proveedor

    Sub New(ByVal nroMovimiento As Long, ByVal com As String, ByVal fecha As DateTime, ByVal monto As Double,
        ByVal cuenta As Cuenta, ByVal tipo As TipoMovimiento, ByVal proveedor As Proveedor)
        MyBase.New(nroMovimiento, com, fecha, monto, cuenta, tipo)
        Me.proveedor = proveedor
    End Sub

    Sub New()

    End Sub

    Public Property proveedor() As Proveedor
        Get
            Return _proveedor
        End Get
        Set(ByVal Value As Proveedor)
            _proveedor = Value
        End Set
    End Property

End Class ' MovimientosCuentaProveedor