'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  Operario.vb
''  Implementation of the Class Operario
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:35 p.m.
''  Original author: martin.perez
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class Operario
    Inherits Usuario

    Private _ProduccionOperador As List(Of ProduccionOperador)
    Private _idOperador As Long

    Sub New()

    End Sub

    Sub New(ByVal id As Long)
        Me.idOperador = id
    End Sub

    Public Property idOperador() As Long
        Get
            Return _idOperador
        End Get
        Set(ByVal value As Long)
            _idOperador = value
        End Set
    End Property


    Public Property produccion() As List(Of ProduccionOperador)
        Get
            Return _ProduccionOperador
        End Get
        Set(ByVal Value As List(Of ProduccionOperador))
            _ProduccionOperador = Value
        End Set
    End Property

End Class ' Operario