'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  OrdenDeCompra.vb
''  Implementation of the Class OrdenDeCompra
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:35 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Option Explicit On

<Serializable()>
Public Class OrdenDeCompra
    Inherits Documento

    Private _nroSucursal As Long
    Private _nroOrdenCompra As Long
    Private _tipoOrdenCompra As String
    Private _proveedor As Proveedor
    Private _lineaOrdenDeCompra As List(Of LineaOrdenDeCompra)
    Private _nroOrden As Long
    Private _tipoOrden As String

    Sub New(ByVal nro As Long, ByVal mov As MovimientosCuenta, ByVal iva As Double, ByVal monto As Double, ByVal fecha As DateTime,
            ByVal borrado As Boolean, ByVal nroOrdenCompra As Long, ByVal nroSucursal As Long, ByVal tipoOrdenCompra As String,
            ByVal proveedor As Proveedor, ByVal lineaOrdenDeCompra As List(Of LineaOrdenDeCompra))
        MyBase.New(nro, mov, iva, fecha, borrado, monto)
        Me.nroOrdenCompra = nroOrdenCompra
        Me.nroSucursal = nroSucursal
        Me.tipoOrdenCompra = tipoOrdenCompra
        Me.proveedor = proveedor
        If Not lineaOrdenDeCompra Is Nothing Then
            For Each linea As LineaOrdenDeCompra In lineaOrdenDeCompra
                linea.ordenDeCompra = Me
            Next
        End If
        Me.lineaOrdenDeCompra = lineaOrdenDeCompra
    End Sub

    Sub New()

    End Sub

    Sub New(ByVal nroOrden As Long, ByVal nroSucursal As Long, ByVal tipoOrden As String)
        Me.nroOrdenCompra = nroOrden
        Me.nroSucursal = nroSucursal
        Me.tipoOrdenCompra = tipoOrden
    End Sub

    Public Property nroSucursal() As Long
        Get
            Return _nroSucursal
        End Get
        Set(ByVal Value As Long)
            _nroSucursal = Value
        End Set
    End Property

    Public Property nroOrdenCompra() As Long
        Get
            Return _nroOrdenCompra
        End Get
        Set(ByVal Value As Long)
            _nroOrdenCompra = Value
        End Set
    End Property

    Public Property tipoOrdenCompra() As String
        Get
            Return _tipoOrdenCompra
        End Get
        Set(ByVal Value As String)
            _tipoOrdenCompra = Value
        End Set
    End Property

    Public Property proveedor() As Proveedor
        Get
            Return _proveedor
        End Get
        Set(ByVal Value As Proveedor)
            _proveedor = Value
        End Set
    End Property

    Public Property lineaOrdenDeCompra() As List(Of LineaOrdenDeCompra)
        Get
            Return _lineaOrdenDeCompra
        End Get
        Set(ByVal value As List(Of LineaOrdenDeCompra))
            _lineaOrdenDeCompra = value
        End Set
    End Property

End Class ' OrdenDeCompra