'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  Patente.vb
''  Implementation of the Class Patente
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:35 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class Patente

    Private _idPatente As Long
    Private _descripcion As String
    Private _permiso As String

    Sub New()

    End Sub

    Sub New(ByVal id As Long, ByVal permiso As String, ByVal descripcion As String)
        Me.patenteId = id
        Me.permiso = permiso
        Me.descripcion = descripcion
    End Sub

    Public Property patenteId() As Long
        Get
            Return _idPatente
        End Get
        Set(ByVal value As Long)
            _idPatente = value
        End Set
    End Property


    Public Property descripcion() As String
        Get
            Return _descripcion
        End Get
        Set(ByVal value As String)
            _descripcion = value
        End Set
    End Property

    Public Property permiso() As String
        Get
            Return _permiso
        End Get
        Set(ByVal value As String)
            _permiso = value
        End Set
    End Property


End Class ' Patente