'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  Pedido.vb
''  Implementation of the Class Pedido
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:35 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class Pedido

    Private _codPedido As Long
    Private _comentario As String
    Private _historicoEstados As List(Of HistoricoEstados)
    Private _tipoPedido As TipoPedido
    Private _estadoActual As EstadoPedido
    Private _trabajos As List(Of Produccion)
    Private _cliente As Cliente

    Private _fechaInicio As Date
    Private _fechaFinal As Date

    Private _borrado As Boolean

    Sub New(ByVal codPedido As Long, ByVal com As String, ByVal hisEstados As List(Of HistoricoEstados),
            ByVal tipo As TipoPedido, ByVal trabajos As List(Of Produccion), ByVal cliente As Cliente,
             ByVal estadoActual As EstadoPedido, ByVal fechaInicio As Date, ByVal fechaFinal As Date)
        Me.codPedido = codPedido
        Me.comentario = com
        Me.historicoEstados = hisEstados
        Me.tipoPedido = tipo
        Me.trabajos = trabajos
        Me.cliente = cliente
        Me.estadoActual = estadoActual
        Me.fechaInicio = fechaInicio
        Me.fechaFinal = fechaFinal

        For Each prod As Produccion In trabajos
            prod.pedido = Me
        Next

        If hisEstados IsNot Nothing Then
            For Each estado As HistoricoEstados In hisEstados
                estado.pedido = Me
            Next
        End If
    End Sub

    Sub New(ByVal codPedido As Long)
        Me.codPedido = codPedido
    End Sub

    Sub New()

    End Sub

    Public Property estadoActual() As EstadoPedido
        Get
            Return _estadoActual
        End Get
        Set(ByVal value As EstadoPedido)
            _estadoActual = value
        End Set
    End Property

    Public Property borrado() As Boolean
        Get
            Return _borrado
        End Get
        Set(ByVal value As Boolean)
            _borrado = value
        End Set
    End Property

    Public Property codPedido() As Long
        Get
            Return _codPedido
        End Get
        Set(ByVal value As Long)
            _codPedido = value
        End Set
    End Property

    Public Property comentario() As String
        Get
            Return _comentario
        End Get
        Set(ByVal Value As String)
            _comentario = Value
        End Set
    End Property

    Public Property historicoEstados() As List(Of HistoricoEstados)
        Get
            Return _historicoEstados
        End Get
        Set(ByVal Value As List(Of HistoricoEstados))
            _historicoEstados = Value
        End Set
    End Property

    Public Property tipoPedido() As TipoPedido
        Get
            Return _tipoPedido
        End Get
        Set(ByVal Value As TipoPedido)
            _tipoPedido = Value
        End Set
    End Property

    Public Property trabajos() As List(Of Produccion)
        Get
            Return _trabajos
        End Get
        Set(ByVal Value As List(Of Produccion))
            _trabajos = Value
        End Set
    End Property

    Public Property cliente() As Cliente
        Get
            Return _cliente
        End Get
        Set(ByVal Value As Cliente)
            _cliente = Value
        End Set
    End Property

    Public Property fechaInicio() As Date
        Get
            Return _fechaInicio
        End Get
        Set(ByVal value As Date)
            _fechaInicio = value
        End Set
    End Property

    Public Property fechaFinal() As Date
        Get
            Return _fechaFinal
        End Get
        Set(ByVal value As Date)
            _fechaFinal = value
        End Set
    End Property

    Public ReadOnly Property porcentajeRealizacion() As Double
        Get
            Dim completados As Integer = 0
            For Each prod As Produccion In trabajos
                If prod.estadoActual.estado.Equals(4) Then
                    completados += 1
                End If
            Next
            Return completados / trabajos.Count
        End Get
    End Property

End Class ' Pedido
