'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  TipoInsumo.vb
''  Implementation of the Class TipoInsumo
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:36 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class TipoInsumo

    Private _tipo As Long
    Private _descripcion As String

    Sub New()

    End Sub

    Sub New(ByVal id As Long)
        Me.tipo = id
    End Sub

    Sub New(ByVal tipo As Long, ByVal descripcion As String)
        Me.tipo = tipo
        Me.descripcion = descripcion
    End Sub

    Public Property descripcion() As String
        Get
            Return _descripcion
        End Get
        Set(ByVal value As String)
            _descripcion = value
        End Set
    End Property

    Public Property tipo() As Long
        Get
            Return _tipo
        End Get
        Set(ByVal Value As Long)
            _tipo = Value
        End Set
    End Property

    Public Overrides Function ToString() As String
        Return Me.descripcion
    End Function

End Class ' TipoInsumo