'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  TipoPedido.vb
''  Implementation of the Class TipoPedido
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:36 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class TipoPedido

    Private _tipoPedido As Long
    Private _descripcion As String

    Sub New(ByVal tipo As Long)
        Me.tipoPedido = tipo
    End Sub

    Sub New()

    End Sub

    Sub New(ByVal tipoPedido As Long, ByVal descripcion As String)
        Me.tipoPedido = tipoPedido
        Me.descripcion = descripcion
    End Sub

    Public Property tipoPedido() As Long
        Get
            Return _tipoPedido
        End Get
        Set(ByVal Value As Long)
            _tipoPedido = Value
        End Set
    End Property

    Public Property descripcion() As String
        Get
            Return _descripcion
        End Get
        Set(ByVal Value As String)
            _descripcion = Value
        End Set
    End Property

End Class ' TipoPedido