'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  TipoMovimiento.vb
''  Implementation of the Class TipoMovimiento
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:36 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable()>
Public Class TipoMovimiento

    Private _tipoMovimiento As Long
    Private _descripcion As String

    Sub New(ByVal tipo As Long)
        Me.tipoMovimiento = tipo
    End Sub

    Sub New()

    End Sub

    Public Property tipoMovimiento() As Long
        Get
            Return _tipoMovimiento
        End Get
        Set(ByVal value As Long)
            _tipoMovimiento = value
        End Set
    End Property

    Public Property descripcion() As String
        Get
            Return _descripcion
        End Get
        Set(ByVal Value As String)
            _descripcion = Value
        End Set
    End Property

    Public Overrides Function ToString() As String
        Return Me.descripcion
    End Function

End Class ' TipoMovimiento