'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  Usuario.vb
''  Implementation of the Class Usuario
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:34:37 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

<Serializable() >
Public Class Usuario


    Private _id As Long
    Private _apellido As String
    Private _mail As String
    Private _nombre As String
    Private _password As String
    Private _telefonoFijo As String
    Private _telefonoMovil As String
    Private _familias As New List(Of Familia)
    Private _patentes As New List(Of Patente)
    Private _bloqueado As Boolean = False

    Sub New(ByVal id As Long, ByVal ap As String, ByVal mail As String, ByVal nombre As String,
                       ByVal pass As String, ByVal telFijo As String, ByVal telMovil As String)
        Me.id = id
        Me.apellido = ap
        Me.mail = mail
        Me.nombre = nombre
        Me.password = pass
        Me.telefonoFijo = telFijo
        Me.telefonoMovil = telMovil
    End Sub

    Sub New()
        ' TODO: Complete member initialization 
    End Sub

    Sub New(ByVal id As Long, ByVal apellido As String, ByVal mail As String, ByVal nombre As String, ByVal contraseña As String,
            ByVal telefonoFijo As String, ByVal telefonoMovil As String, ByVal famialias As List(Of Familia), ByVal permisos As List(Of Patente))
        _id = id
        _apellido = apellido
        _mail = mail
        _nombre = nombre
        _password = contraseña
        _telefonoFijo = telefonoFijo
        _telefonoMovil = telefonoMovil
        _familias = famialias
        _patentes = permisos
    End Sub

    Public Property id() As Long
        Get
            Return _id
        End Get
        Set(ByVal value As Long)
            _id = value
        End Set
    End Property

    Public Property nombre() As String
        Get
            Return _nombre
        End Get
        Set(ByVal Value As String)
            _nombre = Value
        End Set
    End Property

    Public Property apellido() As String
        Get
            Return _apellido
        End Get
        Set(ByVal Value As String)
            _apellido = Value
        End Set
    End Property

    Public Property telefonoMovil() As String
        Get
            Return _telefonoMovil
        End Get
        Set(ByVal Value As String)
            _telefonoMovil = Value
        End Set
    End Property

    Public Property telefonoFijo() As String
        Get
            Return _telefonoFijo
        End Get
        Set(ByVal Value As String)
            _telefonoFijo = Value
        End Set
    End Property

    Public Property mail() As String
        Get
            Return _mail
        End Get
        Set(ByVal Value As String)
            _mail = Value
        End Set
    End Property

    Public Property password() As String
        Get
            Return _password
        End Get
        Set(ByVal Value As String)
            _password = Value
        End Set
    End Property

    Public Property familias() As List(Of Familia)
        Get
            Return _familias
        End Get
        Set(ByVal value As List(Of Familia))
            _familias = value
        End Set
    End Property

    Public Property patentes() As List(Of Patente)
        Get
            Return _patentes
        End Get
        Set(ByVal value As List(Of Patente))
            _patentes = value
        End Set
    End Property

    Public Property bloqueado() As Boolean
        Get
            Return _bloqueado
        End Get
        Set(ByVal value As Boolean)
            _bloqueado = value
        End Set
    End Property

    Public Overrides Function ToString() As String
        Return Me.apellido + " - " + Me.nombre
    End Function
End Class ' Usuario