'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  DataAccesObject.vb
''  Implementation of the Class DataAccesObject
''  Generated by Enterprise Architect
''  Created on:      09-ago-2012 11:28:02 p.m.
''  Original author: Diego
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Imports System.Data.SqlClient
Imports Microsoft.VisualBasic.Logging
Imports System.Text.RegularExpressions



Public Class DataAccesObject

    Dim cadenaConexion As String = System.Web.Configuration.WebConfigurationManager.ConnectionStrings("uniprofConnectionString").ToString
    Dim conexion As New SqlConnection(cadenaConexion)

    ''' 
    ''' <param name="consulta"></param>
    Public Function ejecutarConsulta(ByVal consulta As String) As DataSet
        Dim dataSet As New DataSet()

        Try
            Dim consultas As Array = consulta.Split(";")
            SyncLock GetType(SqlConnection)
                Dim dataAdaptar As New SqlDataAdapter(consulta, conexion)

                For Each tabla As String In consultas
                    dataAdaptar.SelectCommand.CommandText = tabla
                    dataAdaptar.Fill(dataSet, extraerNombreTabla(tabla))
                Next
            End SyncLock
            Console.WriteLine("Save/Update: " + consulta)
        Catch ex As Exception
            Console.WriteLine("***************** Error --> Save: " + consulta)
            Console.WriteLine("                 Stacktrace: " + ex.Message)
        Finally
            conexion.Close()
        End Try

        Return dataSet
    End Function

    ''' 
    ''' <param name="consulta"></param>
    Public Sub saveOrUpdate(ByVal consulta As String)
        Try
            SyncLock GetType(SqlConnection)
                Dim comando As New SqlCommand(consulta, conexion)
                conexion.Open()
                comando.ExecuteNonQuery()
            End SyncLock
            Console.WriteLine("Save/Update: " + consulta)
        Catch ex As Exception
            Console.WriteLine("***************** Error --> Save: " + consulta)
            Console.WriteLine("                 Stacktrace: " + ex.Message)
        Finally
            conexion.Close()
        End Try
    End Sub

    ''' 
    ''' <param name="consulta"></param>
    Public Function consultarValor(ByVal consulta As String) As Object
        Dim result As New Object
        Try
            SyncLock GetType(SqlConnection)
                Dim comando As New SqlCommand(consulta, conexion)
                conexion.Open()
                result = comando.ExecuteScalar()
            End SyncLock
            Console.WriteLine("Save/Update: " + consulta)
        Catch ex As Exception
            Console.WriteLine("***************** Error --> Save: " + consulta)
            Console.WriteLine("                 Stacktrace: " + ex.Message)
        Finally
            conexion.Close()
        End Try

        Return result
    End Function

    Private Function extraerNombreTabla(ByVal tabla As String) As Object
        ' Form regular expression pattern.
        Dim pattern As String = ".*?from\s(.*?)(?:(?:\s.*)|(?:$))"

        ' Get text that matches regular expression pattern.
        Dim matches As MatchCollection = Regex.Matches(tabla, pattern, RegexOptions.IgnorePatternWhitespace)

        Return matches(0).Groups(1).Value
    End Function

    Public Sub grabarDataset(ByVal dataSet As DataSet)
        Try
            Dim dataAdaptar As New SqlDataAdapter()
            SyncLock GetType(SqlConnection)
                dataAdaptar.Update(dataSet)
            End SyncLock

            Console.WriteLine("Actualizacion de disgitos verificadores ")
        Catch ex As Exception
            Console.WriteLine("***************** Error --> Save: ")
            Console.WriteLine("                 Stacktrace: " + ex.Message)
        Finally
            conexion.Close()
        End Try
    End Sub


End Class ' DataAccesObject
